import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import defaultFunc from "./index.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const apiPath = path.join(__dirname, "test", "v2", "api");
const targetPath = path.join(__dirname, "test", "v2");

console.log("Extracting endpoints from:", apiPath);

try {
    const endpoints = defaultFunc({
        toPath: apiPath,
        inTargetPath: targetPath
    });

    console.log(`Successfully extracted ${endpoints.length} endpoints.`);

    // Build the directory tree
    const buildTree = (endpointsArray, basePath) => {
        const root = { name: "api", type: "directory", children: {} };

        endpointsArray.forEach(item => {
            const fullPath = item.endPointContent.fileFullPath;
            // make path relative to basePath
            let relativePath = path.relative(basePath, fullPath).replace(/\\/g, '/');
            const parts = relativePath.split('/');

            let current = root;
            for (let i = 0; i < parts.length; i++) {
                const part = parts[i];
                const isLast = i === parts.length - 1;

                if (isLast) {
                    if (!current.children[part]) {
                        current.children[part] = {
                            name: part,
                            type: "file",
                            relativePath: relativePath,
                            endpoints: []
                        };
                    }
                    current.children[part].endpoints.push({
                        method: item.methodsContent.method,
                        endPoint: item.methodsContent.endPoint,
                        funcToRun: item.methodsContent.funcToRun,
                        line: item.methodsContent.line.trim(),
                        lineNumber: item.methodsContent.lineNumber
                    });
                } else {
                    if (!current.children[part]) {
                        current.children[part] = {
                            name: part,
                            type: "directory",
                            children: {}
                        };
                    }
                    current = current.children[part];
                }
            }
        });

        const convertToArray = (node) => {
            if (node.children) {
                node.children = Object.values(node.children).map(convertToArray);
            }
            return node;
        };

        return Object.values(root.children).map(convertToArray);
    };

    const tree = buildTree(endpoints, targetPath);

    // Write to docs/data.js and docs/v1/data.js
    const dataJsContent = `// Auto-generated by build-docs.js - Do not edit manually\nwindow.endpointsTreeData = ${JSON.stringify(tree, null, 2)};\n`;

    const docsDataPath = path.join(__dirname, "docs", "data.js");
    const docsV1DataPath = path.join(__dirname, "docs", "v1", "data.js");

    // Ensure directories exist
    fs.mkdirSync(path.dirname(docsDataPath), { recursive: true });
    fs.mkdirSync(path.dirname(docsV1DataPath), { recursive: true });

    fs.writeFileSync(docsDataPath, dataJsContent, "utf8");
    fs.writeFileSync(docsV1DataPath, dataJsContent, "utf8");

    console.log("Documentation data generated successfully at:");
    console.log(" -", docsDataPath);
    console.log(" -", docsV1DataPath);
} catch (error) {
    console.error("Error generating documentation data:", error);
    process.exit(1);
}
